### ISSUE TITLE
The relative path in install.sh for copying files is incorrect

### ISSUE THREAD

**Issue by dacitsme** [nicolodiamante/icloud-nosync#1]
In utils/install.sh
Replace

`cp -r ./scripts/iCloud\ No\ Sync.workflow "${APPLE_SERVICES}"`
`cp -r ./scripts/iCloud\ Sync.workflow "${APPLE_SERVICES}"`

with

`cp -r ../scripts/iCloud\ No\ Sync.workflow "${APPLE_SERVICES}"`
`cp -r ../scripts/iCloud\ Sync.workflow "${APPLE_SERVICES}"`

**Comment by nicolodiamante** [comment]
Thanks for the hint!

**Comment by nicolodiamante** [comment]
Thanks for the hint!
